server:
  port: 8080
swagger:
  base-path: /**
  base-package: 'com.example'
  title: 'spring-boot-swagger-demo'
  description: '基于Swagger构建的SpringBoot RESTApi 文档'
  version: '1.0'
  contact:
    name: 'xxx'
    url: 'http://www.xxx.cn'
    email: 'xxx@xxx.com'
